### ISSUE TITLE
Convert frontend to Ember

### ISSUE THREAD

**Issue by Dhaulagiri** [Dhaulagiri/hardclimbs#19]
Todo:
- [x] Initial working version (#31)
- [ ] Rewrite views in Ember (#22)
  - [ ] Sorting (#27)
  - [ ] Pagination (#28)
  - [ ] Map (#29)
  - [ ] Friendly URLS (#30)
- [ ] Convert existing controllers to API (#23)
  - [ ] How to lockdown new API as read only for everyone but specific users (#24)
- [x] How to deploy (#20)
- [ ] Redesign the homepage (#25)
- [ ] Ensure typeahead search still works (#26)
- [ ] Embed of images/videos (#32)
- [ ] SEO (#21)
